import type { Story, StoryMeta } from "$lib/types";

export { translations } from "./translations";

export const storyMetas: StoryMeta[] = [
	{
		id: 1,
		title: "The Lost Key",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "🔑",
		gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
		desc: "Une histoire mystérieuse sur une clé perdue",
		duration: "5 min",
		words: 120,
		category: "adventure",
		tags: ["past-tense", "home", "mystery", "A1"],
	},
	{
		id: 2,
		title: "The Magic Bookshop",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "📚",
		gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
		desc: "Une librairie enchantée qui apparaît la nuit",
		duration: "8 min",
		words: 200,
		category: "fantasy",
		tags: ["past-tense", "past-continuous", "descriptive", "A2-B1"],
	},
	{
		id: 3,
		title: "The Time Traveler",
		level: "Avancé",
		levelColor: "#ff6b6b",
		emoji: "⏰",
		gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
		desc: "Un voyage dans le temps qui change tout",
		duration: "12 min",
		words: 310,
		category: "sci-fi",
		tags: ["past-perfect", "passive-voice", "complex-sentences", "B1-B2"],
	},
	{
		id: 4,
		title: "A Day at the Market",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "🛒",
		gradient: "linear-gradient(135deg, #a8e063 0%, #56ab2f 100%)",
		desc: "Une journée de courses au marché local",
		duration: "5 min",
		words: 150,
		category: "daily-life",
		tags: ["present-tense", "food", "numbers", "A1"],
	},
	{
		id: 5,
		title: "The Perfect Recipe",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "🍳",
		gradient: "linear-gradient(135deg, #f5af19 0%, #f12711 100%)",
		desc: "Apprendre à cuisiner un plat simple en anglais",
		duration: "6 min",
		words: 170,
		category: "food",
		tags: ["imperative", "cooking", "kitchen-vocabulary", "A1-A2"],
	},
	{
		id: 6,
		title: "Lost in the City",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "🏙️",
		gradient: "linear-gradient(135deg, #667db6 0%, #0082c8 50%, #667db6 100%)",
		desc: "Se repérer dans une grande ville étrangère",
		duration: "8 min",
		words: 240,
		category: "travel",
		tags: ["directions", "past-continuous", "polite-requests", "A2-B1"],
	},
	{
		id: 7,
		title: "The Old Oak Tree",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "🌳",
		gradient: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
		desc: "Les quatre saisons racontées par un vieux chêne",
		duration: "7 min",
		words: 220,
		category: "nature",
		tags: ["present-perfect", "descriptive", "seasons", "B1"],
	},
	{
		id: 8,
		title: "The Digital Detective",
		level: "Avancé",
		levelColor: "#ff6b6b",
		emoji: "💻",
		gradient: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
		desc: "Une enquête numérique pleine de suspense",
		duration: "12 min",
		words: 340,
		category: "technology",
		tags: ["conditional", "passive-voice", "technology", "B1-B2"],
	},
	{
		id: 9,
		title: "The Championship Match",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "⚽",
		gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
		desc: "Un match de football inoubliable",
		duration: "9 min",
		words: 260,
		category: "sports",
		tags: ["past-tense", "sports", "emotions", "A2-B1"],
	},
	{
		id: 10,
		title: "A Letter from Abroad",
		level: "Avancé",
		levelColor: "#ff6b6b",
		emoji: "✉️",
		gradient: "linear-gradient(135deg, #c94b4b 0%, #4b134f 100%)",
		desc: "Une correspondance entre deux amis de pays différents",
		duration: "14 min",
		words: 400,
		category: "travel",
		tags: ["past-perfect", "formal-register", "culture", "B2"],
	},
	{
		id: 11,
		title: "The Secret Garden",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "🌿",
		gradient: "linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)",
		desc: "Un jardin caché derrière une vieille maison",
		duration: "5 min",
		words: 130,
		category: "nature",
		tags: ["present-simple", "nature", "discovery", "A1"],
	},
	{
		id: 12,
		title: "The Coffee Shop Mystery",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "☕",
		gradient: "linear-gradient(135deg, #834d18 0%, #e0a96d 100%)",
		desc: "Un mystère se cache derrière un café de quartier",
		duration: "10 min",
		words: 240,
		category: "mystery",
		tags: ["past-tense", "conditionals", "mystery", "A2-B1"],
	},
	{
		id: 13,
		title: "A Rainy Day Adventure",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "🌧️",
		gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
		desc: "Une journée pluvieuse pleine de surprises",
		duration: "5 min",
		words: 120,
		category: "daily-life",
		tags: ["present-continuous", "weather", "daily-life", "A1"],
	},
	{
		id: 14,
		title: "The Music Festival",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "🎵",
		gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
		desc: "Un festival de musique qui change une vie",
		duration: "10 min",
		words: 250,
		category: "culture",
		tags: ["past-tense", "music", "friendship", "A2-B1"],
	},
	{
		id: 15,
		title: "The Last Train",
		level: "Avancé",
		levelColor: "#ff6b6b",
		emoji: "🚂",
		gradient: "linear-gradient(135deg, #2c3e50 0%, #3498db 100%)",
		desc: "Une course contre la montre à la gare",
		duration: "12 min",
		words: 320,
		category: "adventure",
		tags: ["past-perfect", "conditionals", "suspense", "B1-B2"],
	},
	{
		id: 16,
		title: "Icarus and the Sun",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "☀️",
		gradient: "linear-gradient(135deg, #f5af19 0%, #f12711 100%)",
		desc: "Le garçon qui vola trop près du soleil",
		duration: "5 min",
		words: 135,
		category: "mythology",
		tags: ["past-simple", "direct-speech", "greek-myth", "A1-A2"],
	},
	{
		id: 17,
		title: "Pandora's Box",
		level: "Débutant",
		levelColor: "#6bcf7f",
		emoji: "📦",
		gradient: "linear-gradient(135deg, #6a3093 0%, #a044ff 100%)",
		desc: "La femme qui libéra tous les maux du monde",
		duration: "5 min",
		words: 155,
		category: "mythology",
		tags: ["past-simple", "because", "greek-myth", "A2"],
	},
	{
		id: 18,
		title: "Perseus and Medusa",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "⚔️",
		gradient: "linear-gradient(135deg, #373b44 0%, #4286f4 100%)",
		desc: "Le héros qui vainquit le monstre aux serpents",
		duration: "8 min",
		words: 245,
		category: "mythology",
		tags: ["past-simple", "relative-clauses", "greek-myth", "A2-B1"],
	},
	{
		id: 19,
		title: "Theseus and the Minotaur",
		level: "Intermédiaire",
		levelColor: "#ffd93d",
		emoji: "🐂",
		gradient: "linear-gradient(135deg, #2c1654 0%, #5c2a9d 100%)",
		desc: "Le labyrinthe et la bête mi-homme mi-taureau",
		duration: "9 min",
		words: 265,
		category: "mythology",
		tags: ["past-simple", "conditionals", "greek-myth", "B1"],
	},
	{
		id: 20,
		title: "Orpheus and Eurydice",
		level: "Avancé",
		levelColor: "#ff6b6b",
		emoji: "🎵",
		gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
		desc: "L'amour plus fort que la mort, presque",
		duration: "12 min",
		words: 345,
		category: "mythology",
		tags: ["past-perfect", "conditionals", "complex-sentences", "B1-B2"],
	},
];

const storyModules = import.meta.glob<{ default: Story }>("./story-*.ts");

export async function loadStory(id: number): Promise<Story> {
	const key = `./story-${id}.ts`;
	const loader = storyModules[key];
	if (!loader) throw new Error(`Story ${id} not found`);
	const mod = await loader();
	return mod.default;
}
